=== Spirit-of-Oberon/oo2c/rsrc/OOC/xml/interface-description.dtd
<?xml version='1.0' encoding='US-ASCII'?>

<!ENTITY % oberon-doc SYSTEM "oberon-doc.dtd">
%oberon-doc;

<!ENTITY % reference-attributes
  "module CDATA #REQUIRED
   name CDATA #REQUIRED 
   class CDATA #REQUIRED
   href CDATA #REQUIRED">


<!ELEMENT interface-description (oberon-doc?,
                                 import-decl*, 
                                 (const-decl|type-decl|var-decl)*,
                                 procedure*,
                                 class*,
                                 module-ref*)>
<!ATTLIST interface-description name CDATA #REQUIRED
                                id   CDATA #REQUIRED>

<!ELEMENT class (type-decl*, procedure*, base-class*, known-extension*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT base-class ((inherited-field | inherited-method)*, base-class?)>
<!ATTLIST base-class module CDATA #REQUIRED
                     class CDATA #REQUIRED
                     href CDATA #REQUIRED>

<!ELEMENT inherited-field EMPTY>
<!ATTLIST inherited-field %reference-attributes;>

<!ELEMENT inherited-method EMPTY>
<!ATTLIST inherited-method %reference-attributes;>

<!ELEMENT redefined-method EMPTY>
<!ATTLIST redefined-method %reference-attributes;>

<!ELEMENT known-extension EMPTY>
<!ATTLIST known-extension %reference-attributes;>

<!ELEMENT doc-inherited-from EMPTY>
<!ATTLIST doc-inherited-from %reference-attributes;>


<!ELEMENT import-decl (oberon-doc?)>
<!ATTLIST import-decl name CDATA #REQUIRED
                      id ID #REQUIRED
                      export (yes|no|read-only) #REQUIRED
                      module CDATA #REQUIRED>

<!ELEMENT const-decl (oberon-doc?)>
<!ATTLIST const-decl name CDATA #REQUIRED
                     id ID #REQUIRED
                     export (yes|no|read-only) #REQUIRED
                     value CDATA #REQUIRED>

<!ELEMENT type-decl (oberon-doc?, type)>
<!ATTLIST type-decl name CDATA #REQUIRED
                    id ID #REQUIRED
                    export (yes|no|read-only) #REQUIRED>

<!ELEMENT var-decl (oberon-doc?, type)>
<!ATTLIST var-decl name CDATA #REQUIRED
                   id ID #REQUIRED
                   export (yes|no|read-only) #REQUIRED>

<!ELEMENT receiver-decl (oberon-doc?, type)>
<!ATTLIST receiver-decl name CDATA #REQUIRED
                        id ID #REQUIRED
                        export (yes|no|read-only) #REQUIRED
                        variable-parameter (yes|no) #REQUIRED>

<!ELEMENT parameter-decl (oberon-doc?, type)>
<!ATTLIST parameter-decl name CDATA #REQUIRED
                         id ID #REQUIRED
                         export (yes|no|read-only) #REQUIRED
                         variable-parameter (yes|no) #REQUIRED>

<!ELEMENT field-decl (oberon-doc?, type)>
<!ATTLIST field-decl name CDATA #REQUIRED
                     id ID #IMPLIED
                     export (yes|no|read-only) #REQUIRED>
<!-- A field declaration may appear multiple times in the description
file for degenerate cases like "VAR x*, y*: RECORD a*: CHAR", where
the field "a" appears in the XML output both within the declaration
of "x" and of "y".  Because id attributes must be unique, only the
first declaration is assigned an id.  -->


<!ELEMENT procedure ((doc-inherited-from?, oberon-doc)?,
                     formal-parameters, redefined-method*)>
<!ATTLIST procedure name CDATA #REQUIRED
                    id ID #REQUIRED
                    export (yes|no|read-only) #REQUIRED>



<!ELEMENT type-name EMPTY>
<!ATTLIST type-name module CDATA ""
                    name CDATA #REQUIRED
                    href CDATA #IMPLIED>

<!ELEMENT pointer (pointer-base)>

<!ELEMENT pointer-base (type-name|array|record)>

<!ELEMENT array (length?, element-type)>

<!ELEMENT length (#PCDATA)>

<!ELEMENT element-type (type-name|array|record|pointer|formal-parameters)>

<!ELEMENT record (field-decl*)>

<!ELEMENT formal-parameters (receiver-decl?, parameter-decl*,
                             result-type?, exceptions?)>

<!ELEMENT result-type (type-name)>

<!ELEMENT exceptions (type-name)*>

<!ELEMENT type (type-name|pointer|array|record|formal-parameters)>


<!ELEMENT module-ref (ref-target+)>
<!ATTLIST module-ref name CDATA #REQUIRED>

<!ELEMENT ref-target EMPTY>
<!ATTLIST ref-target type (html) #REQUIRED
                     relative-uri CDATA #REQUIRED>

<!--

Some words regarding the class stuff: Oberon-2's notion of classes is
rather vague.  The border between a class and a record is fuzzy, and a
class may be based on a pointer type or just on a record type.
Additionally, there is no established notation to associate a class
with its constructors.

All in all, this situation imposes some problems when one tries to
extract documentation for a class from source code in an automated
way.  All the tidbits of information that make up a class must be
collected.  This includes the record type, the associated pointer type
(if present), any constructor functions, and (if present)
initialization procedures used by the constructors.  

I don't want to make things too complicated, so I will try to get
along for the moment with a set of simple rules.  These rules only
cover the situation where a class is an heap object, that is, a record
type and a pointer type.

1. A record is classified as a "class" if it is defined on the module
level, has exactly one pointer type declaration refering to it, and if
it
  a) extends an existing record, or
  b) if there are any type-bound procedures in the same module that use
  it as receiver type.

2. The class name is either the name of the record type, or, if the
pointer's type name is a prefix of the record type, the pointer name.

3. All type-bound procedures belong to the class of their receiver
type.

4. All normal procedures that have the class pointer type as their
result are assumed to be constructors of this class.  The result type
must be defined in the same module as the procedure.

5. All normal procedures
  a) whose name is "Init", or whose name begins with "Init", 
  b) whose first argument is of a class type from the same module, and
  c) and that are not function procedures,
are assumed to be auxiliary functions or constructors.  They are
considered to be part of the class definition.

There may be additional constants, variables, and type definitions
that logically are part of a class definition.  They appear in the
module documentation.  There is no simple way to connect them to a
class without hints provided by the programmer.

-->

=== Spirit-of-Oberon/oo2c/tests/interface/wf/out-xml/M015.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>
<!DOCTYPE interface-description SYSTEM '../../../../../rsrc/OOC/xml/interface-description.dtd'>
<interface-description name='M015' id=''>
  <type-decl name='ArgList' id='ArgList' export='no'>
    <type>
      <pointer>
        <pointer-base>
          <array>
            <element-type>
              <pointer>
                <pointer-base>
                  <array>
                    <element-type>
                      <type-name module='#predef' name='CHAR'/>
                    </element-type>
                  </array>
                </pointer-base>
              </pointer>
            </element-type>
          </array>
        </pointer-base>
      </pointer>
    </type>
  </type-decl>
  <class name='OptionTemplate'>
    <type-decl name='OptionTemplate' id='OptionTemplate' export='yes'>
      <type>
        <pointer>
          <pointer-base>
            <type-name name='OptionTemplateDesc' href='#OptionTemplateDesc'/>
          </pointer-base>
        </pointer>
      </type>
    </type-decl>
    <type-decl name='OptionTemplateDesc' id='OptionTemplateDesc' export='no'>
      <type>
        <record>
          <field-decl name='optTemplate' id='OptionTemplateDesc.optTemplate' export='read-only'>
            <type>
              <type-name module='#predef' name='CHAR'/>
            </type>
          </field-decl>
        </record>
      </type>
    </type-decl>
  </class>
  <class name='Command'>
    <type-decl name='Command' id='Command' export='yes'>
      <type>
        <pointer>
          <pointer-base>
            <type-name name='CommandDesc' href='#CommandDesc'/>
          </pointer-base>
        </pointer>
      </type>
    </type-decl>
    <type-decl name='CommandDesc' id='CommandDesc' export='no'>
      <type>
        <record>
          <field-decl name='template' id='CommandDesc.template' export='read-only'>
            <oberon-doc>
              <summary>Text template, that is used to create the XML fragment.</summary>
              <p pad-after='yes' no-indent='yes'>Text template, that is used to create the XML fragment.  Any references $1, $2, ..., $9 are replaced with the arguments from <oberon-field href='#CommandDesc.argList'>argList</oberon-field>.</p>
            </oberon-doc>
            <type>
              <type-name name='OptionTemplate' href='#OptionTemplate'/>
            </type>
          </field-decl>
          <field-decl name='argList' id='CommandDesc.argList' export='read-only'>
            <oberon-doc>
              <summary>Arguments of the command line option.</summary>
              <p pad-after='yes' no-indent='yes'>Arguments of the command line option.  If the option has no arguments, <samp>LEN(argList^)</samp> is zero.</p>
            </oberon-doc>
            <type>
              <type-name name='ArgList' href='#ArgList'/>
            </type>
          </field-decl>
        </record>
      </type>
    </type-decl>
  </class>
</interface-description>

=== Spirit-of-Oberon/oo2c/tests/interface/wf/out-xml/M016.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>
<!DOCTYPE interface-description SYSTEM '../../../../../rsrc/OOC/xml/interface-description.dtd'>
<interface-description name='M016' id=''>
  <class name='C0'>
    <type-decl name='C0' id='C0' export='yes'>
      <type>
        <pointer>
          <pointer-base>
            <type-name name='C0Desc' href='#C0Desc'/>
          </pointer-base>
        </pointer>
      </type>
    </type-decl>
    <type-decl name='C0Desc' id='C0Desc' export='no'>
      <type>
        <record/>
      </type>
    </type-decl>
    <procedure name='P' id='C0Desc.P' export='yes'>
      <oberon-doc>
        <summary><oberon-param href='#C0Desc.P.xxx'>xxx</oberon-param>, <oberon-param href='#C0Desc.P.y'>y</oberon-param></summary>
        <p pad-after='yes' no-indent='yes'><oberon-param href='#C0Desc.P.xxx'>xxx</oberon-param>, <oberon-param href='#C0Desc.P.y'>y</oberon-param></p>
      </oberon-doc>
      <formal-parameters>
        <receiver-decl name='xxx' id='C0Desc.P.xxx' export='no' variable-parameter='no'>
          <type>
            <type-name name='C0' href='#C0'/>
          </type>
        </receiver-decl>
        <parameter-decl name='y' id='C0Desc.P.y' export='no' variable-parameter='no'>
          <type>
            <type-name module='#predef' name='CHAR'/>
          </type>
        </parameter-decl>
      </formal-parameters>
    </procedure>
    <known-extension module='M016' name='C1Desc' class='C1' href='#C1Desc'/>
    <known-extension module='M016' name='C2Desc' class='C2' href='#C2Desc'/>
  </class>
  <class name='C1'>
    <type-decl name='C1' id='C1' export='yes'>
      <type>
        <pointer>
          <pointer-base>
            <type-name name='C1Desc' href='#C1Desc'/>
          </pointer-base>
        </pointer>
      </type>
    </type-decl>
    <type-decl name='C1Desc' id='C1Desc' export='no'>
      <type>
        <record>
          <field-decl name='a' id='C1Desc.a' export='read-only'>
            <type>
              <type-name module='#predef' name='INTEGER'/>
            </type>
          </field-decl>
        </record>
      </type>
    </type-decl>
    <procedure name='P' id='C1Desc.P' export='yes'>
      <doc-inherited-from module='M016' name='P' class='C0' href='#C0Desc.P'/>
      <oberon-doc>
        <summary><oberon-param href='#C1Desc.P.c1'>c1</oberon-param>, <oberon-param href='#C1Desc.P.b'>b</oberon-param></summary>
        <p pad-after='yes' no-indent='yes'><oberon-param href='#C1Desc.P.c1'>c1</oberon-param>, <oberon-param href='#C1Desc.P.b'>b</oberon-param></p>
      </oberon-doc>
      <formal-parameters>
        <receiver-decl name='c1' id='C1Desc.P.c1' export='no' variable-parameter='no'>
          <type>
            <type-name name='C1' href='#C1'/>
          </type>
        </receiver-decl>
        <parameter-decl name='b' id='C1Desc.P.b' export='no' variable-parameter='no'>
          <type>
            <type-name module='#predef' name='CHAR'/>
          </type>
        </parameter-decl>
      </formal-parameters>
      <redefined-method module='M016' name='P' class='C0' href='#C0Desc.P'/>
    </procedure>
    <base-class module='M016' class='C0' href='#C0'>
      <inherited-method module='M016' name='P' class='C0' href='#C0Desc.P'/>
    </base-class>
    <known-extension module='M016' name='C2Desc' class='C2' href='#C2Desc'/>
  </class>
  <class name='C2'>
    <type-decl name='C2' id='C2' export='yes'>
      <type>
        <pointer>
          <pointer-base>
            <type-name name='C2Desc' href='#C2Desc'/>
          </pointer-base>
        </pointer>
      </type>
    </type-decl>
    <type-decl name='C2Desc' id='C2Desc' export='no'>
      <type>
        <record/>
      </type>
    </type-decl>
    <base-class module='M016' class='C1' href='#C1'>
      <inherited-method module='M016' name='P' class='C1' href='#C1Desc.P'/>
      <inherited-field module='M016' name='a' class='C1' href='#C1Desc.a'/>
      <base-class module='M016' class='C0' href='#C0'/>
    </base-class>
  </class>
</interface-description>

=== Spirit-of-Oberon/oo2c/tests/interface/wf/out-xml/M002.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>
<!DOCTYPE interface-description SYSTEM '../../../../../rsrc/OOC/xml/interface-description.dtd'>
<interface-description name='M002' id=''>
  <procedure name='Length' id='Length' export='yes'>
    <formal-parameters>
      <parameter-decl name='stringVal' id='Length.stringVal' export='no' variable-parameter='no'>
        <type>
          <array>
            <element-type>
              <type-name module='#predef' name='CHAR'/>
            </element-type>
          </array>
        </type>
      </parameter-decl>
      <result-type>
        <type-name module='#predef' name='INTEGER'/>
      </result-type>
    </formal-parameters>
  </procedure>
  <procedure name='Assign' id='Assign' export='yes'>
    <formal-parameters>
      <parameter-decl name='source' id='Assign.source' export='no' variable-parameter='no'>
        <type>
          <array>
            <element-type>
              <type-name module='#predef' name='CHAR'/>
            </element-type>
          </array>
        </type>
      </parameter-decl>
      <parameter-decl name='destination' id='Assign.destination' export='no' variable-parameter='yes'>
        <type>
          <array>
            <element-type>
              <type-name module='#predef' name='CHAR'/>
            </element-type>
          </array>
        </type>
      </parameter-decl>
    </formal-parameters>
  </procedure>
  <procedure name='Extract' id='Extract' export='yes'>
    <formal-parameters>
      <parameter-decl name='source' id='Extract.source' export='no' variable-parameter='no'>
        <type>
          <array>
            <element-type>
              <type-name module='#predef' name='CHAR'/>
            </element-type>
          </array>
        </type>
      </parameter-decl>
      <parameter-decl name='startPos' id='Extract.startPos' export='no' variable-parameter='no'>
        <type>
          <type-name module='#predef' name='INTEGER'/>
        </type>
      </parameter-decl>
      <parameter-decl name='numberToExtract' id='Extract.numberToExtract' export='no' variable-parameter='no'>
        <type>
          <type-name module='#predef' name='INTEGER'/>
        </type>
      </parameter-decl>
      <parameter-decl name='destination' id='Extract.destination' export='no' variable-parameter='yes'>
        <type>
          <array>
            <element-type>
              <type-name module='#predef' name='CHAR'/>
            </element-type>
          </array>
        </type>
      </parameter-decl>
    </formal-parameters>
  </procedure>
</interface-description>
