=== Spirit-of-Oberon/oo2c/rsrc/OOC/TestFramework/test-setup.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY % URI "CDATA" >

<!ELEMENT test-setup
  (machine,
   operating-system,
   processor,
   test-suite) >

<!ELEMENT machine EMPTY>
<!ATTLIST machine
          model CDATA #REQUIRED
          cpu CDATA #REQUIRED
          ram CDATA #REQUIRED>

<!ELEMENT operating-system (os-component*) >
<!ATTLIST operating-system
          name CDATA #REQUIRED 
          version CDATA #REQUIRED >

<!ELEMENT os-component (#PCDATA) >
<!ATTLIST os-component
          name CDATA #REQUIRED >

<!ELEMENT processor EMPTY >
<!ATTLIST processor
          name CDATA #REQUIRED
          version CDATA #REQUIRED
          command CDATA #REQUIRED
          config-file %URI; #IMPLIED
          flags CDATA #REQUIRED 
          working-dir CDATA #REQUIRED >

<!ELEMENT test-suite EMPTY >
<!ATTLIST test-suite
          uri %URI; #REQUIRED >

=== Spirit-of-Oberon/oo2c/rsrc/OOC/TestFramework/test-setup.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE test-setup SYSTEM "test-setup.dtd">

<test-setup lang="O1">
  <machine model="IBM ThinkPad 600E"
	   cpu="Mobile Pentium II, stepping 10"
	   ram="288 MB" />
  
  <operating-system name="Linux"
		    version="2.4.2-pre4 i686 unknown">
    <os-component name="libc">/lib/libc-2.2.2.so</os-component>
    <os-component name="libgc">unknown</os-component>
    <os-component name="cc">gcc 2.95.2</os-component>
  </operating-system>
    
  <processor name="oo2c"
	     version="1.5.5.1"
	     command="/usr/bin/Oo2c"
	     config-file="./sample-oo2crc"
	     flags="-Ov"
	     working-dir="/tmp/ooc-tests" 
	     filter-command="/usr/bin/Ooef" />

  <test-suite uri="testsuite.xml" />
</test-setup>

=== Spirit-of-Oberon/oo2c/tests/hostess-ooc1/test-setup.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE test-setup SYSTEM "../../rsrc/OOC/TestFramework/test-setup.dtd">

<test-setup lang="O2">
  <machine model="IBM ThinkPad 600E"
	   cpu="Mobile Pentium II, stepping 10"
	   ram="288 MB" />
  
  <operating-system name="Linux"
		    version="2.4.8 i686 unknown">
    <os-component name="libc">/lib/libc-2.2.2.so</os-component>
    <os-component name="libgc">unknown</os-component>
    <os-component name="cc">gcc 2.95.2</os-component>
  </operating-system>
    
  <processor name="oo2c"
	     version="1.5.5.3"
	     command="/usr/bin/Oo2c"
	     config-file="./sample-oo2crc"
	     flags="--config ../sample-oo2crc -Ow"
	     working-dir="./wd" 
	     filter-command="/usr/bin/Ooef" 
	     diff-command="diff -u" />

  <test-suite uri="testsuite.xml" />
</test-setup>
